# Generated by Django 4.2.5 on 2024-01-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed_centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('contact', models.CharField(max_length=25, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Обр. центры - контакт',
                'verbose_name_plural': 'Обр. центры - контакты',
                'ordering': ('id',),
            },
        ),
    ]
