version: "3"
services:
  postgres:
    container_name: notpal_prod_postgres
    networks:
      - notpal_prod_network

  api:
    container_name: notpal_prod_django
    expose:
      - 8017
    volumes:
      - ./media_storage:/app/media_storage
    command: gunicorn core.wsgi --bind 0.0.0.0:8017 --workers 3
    networks:
      - notpal_prod_network

  nginx:
    container_name: notpal_prod_nginx
    build: ./nginx
    ports:
      - 8086:8001
    depends_on:
      - api
    volumes:
      - ./static_root:/static_root
      - ./media_storage:/media_storage

    networks:
      - notpal_prod_network

  redis:
    container_name: notpal_prod_redis
    image: redis:7.2.2-alpine
    expose:
      - 6379

    networks:
      - notpal_prod_network

  celery:
    container_name: notpal_prod_celery
    build:
      context: ./backend
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - api
    env_file:
      - ./backend/.env

    networks:
      - notpal_prod_network

volumes:
    pgdata:
    static_root:
    media_storage:

networks:
  notpal_prod_network:
    external: true
